gripper_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - gripper_right_finger_joint
    - gripper_left_finger_joint

  constraints:
    goal_time: &goal_time_constraint 0.6
    stopped_velocity_tolerance: &stopped_velocity_constraint 5.0
    torso_1_joint:
      goal: &goal_pos_constraint 0.02
    torso_2_joint:
      goal: *goal_pos_constraint
