teleop:
  move:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: cmd_vel
    axis_mappings:
      -
        axis: 1
        target: linear.x
        scale: 1.0
      -
        axis: 2
        target: angular.z
        scale: 1.0

  joy_priority:
    type: action
    action_name: joy_priority_action
    buttons: [0]

  joy_turbo_decrease:
    type: action
    action_name: joy_turbo_decrease
    buttons: [1, 4, 5]

  joy_turbo_increase:
    type: action
    action_name: joy_turbo_increase
    buttons: [3, 4, 5]

  joy_turbo_angular_decrease:
    type: action
    action_name: joy_turbo_angular_decrease
    buttons: [0, 4, 5]

  joy_turbo_angular_increase:
    type: action
    action_name: joy_turbo_angular_increase
    buttons: [2, 4, 5]

  joy_turbo_reset:
    type: action
    action_name: joy_turbo_reset
    buttons: [4, 5, 7]

  # Disable speed_limit example
  # @todo duration param is not taken
  #speed_limit_disable:
  #  type: action
  #  action_name: speed_limit/disable
  #  duration: 10.0
  #  buttons: [4, 5, 6, 7]
