actuators:
  raw_data:
    position_port: act_position
    effort_port: act_current
    #position_cmd_port: ref_position #commented because no jnt pos transmission available on pmb2 (urdf)
    velocity_cmd_port: ref_velocity
    effort_cmd_port: ref_current
    current_limit_cmd_port: ref_limit_current

e_stop:
  raw_data:
    e_stop_port: emergency_stop_state
