priority: false

turbo:
  linear_forward_min  : 0.10
  linear_forward_max  : 0.50
  linear_backward_min : 0.10
  linear_backward_max : 0.30
  angular_min : !degrees 15.0
  angular_max : !degrees 80.0
  steps       : 6
