# From http://support.robotis.com/en/product/dynamixel/ax_series/dxl_ax_actuator.htm#Actuator_Address_1A
# Compliance Slope is set in 7 steps, the higher the value, the more flexibility is obtained.
# Step |       Data Value      | Data Representative Value
#  1   |   0(0x00) ~ 3(0x03)   | 2 (0x02)
#  2   |   4(0x04) ~ 7(0x07)   | 4 (0x04)
#  3   |   8(0x08) ~ 15(0x0F)  | 8 (0x08)
#  4   |  16(0x10) ~ 31(0x1F)  | 16 (0x10)
#  5   |  32(0x20) ~ 63(0x3F)  | 32 (0x20)
#  6   |  64(0x40) ~ 127(0x7F) | 64 (0x40)
#  7   | 128(0x80) ~ 254(0xFE) | 128 (0x80)

dynamixel_parameters:
  head_1_joint:
    id: 1
    # Compliance slope is related to the torque when we are very close to a goal
    compliance_slope: 50
    invert_commands: false
    # value in between 0.0 and 1.0 to limit the torque of the motor representing
    # % of max torque
    torque_limit: 0.5
  head_2_joint:
    id: 2
    compliance_slope: 50
    # The motor is mounted inverted
    invert_commands: true
    torque_limit: 0.8
