arm_current_limit_controller:
  type: "pal_ros_controllers/CurrentLimitController"
  actuators:
    - arm_1_motor
    - arm_2_motor
    - arm_3_motor
    - arm_4_motor
    - arm_5_motor
    - arm_6_motor
    - arm_7_motor

hand_current_limit_controller:
  type: "pal_ros_controllers/CurrentLimitController"
  actuators:
    - hand_thumb_motor
    - hand_index_motor
    - hand_mrl_motor

wheels_current_limit_controller:
  type: "pal_ros_controllers/CurrentLimitController"
  actuators:
    - wheel_left_motor
    - wheel_right_motor