hand_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - hand_thumb_joint
    - hand_index_joint
    - hand_mrl_joint

  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.75
    hand_thumb_joint:
      goal: &hand_goal_pos_constraint 0.3
    hand_index_joint:
      goal: 0.6
    hand_mrl_joint:
      goal: *hand_goal_pos_constraint
  stop_trajectory_duration: 0.0
