gripper_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - gripper_finger_joint

  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 5.0
    gripper_finger_joint:
      goal: 0.02
